# Generated by Django 2.1.4 on 2019-01-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health',
            field=models.CharField(default='Good', max_length=255),
            preserve_default=False,
        ),
    ]
